---
output:
  pdf_document: default
  html_document: default
---

```{r}
#install.packages("ggplot2")
#install.packages("matlib")
#install.packages("rsample")
#install.packages("plotly")
#install.packages("Hmisc")
#install.packages("tidyr")
```

```{r}
library(matlib)
library(ggplot2)
library(rsample)
library(plotly)
library(Hmisc)
library(tidyr)
```

```{r}
time_file = read.csv("./time_1673241270748.csv", header = F, skip = 1)
X_file = read.csv("./X_1673241366257.csv", header = F, skip = 1)
y_file = read.csv("./y_1673241374123.csv", header = F, skip = 1)

```

```{r}
time = as.matrix(time_file)
colnames(time)<-c("time")
time[1:5,]
```

```{r}
X = as.matrix(X_file)
colnames(X)<-c("X1", "X2", "X3", "X4")
X[1:5,]
```

```{r}
y = as.matrix(y_file)
colnames(y)<-c("y")
y[1:5,]
```

```{r}
df = data.frame(cbind(time, X, y ))
df[1:5,]
```

```{r}
describe(df["time"])
```

```{r}
plot_ly(df) %>%
  add_trace( x=~time, y=~X1,type = "scatter",mode = "lines", name = "X1") %>%  
  add_trace( x=~time, y=~X2,type = "scatter",mode = "lines", name = "X2") %>%  
  add_trace( x=~time, y=~X3,type = "scatter",mode = "lines", name = "X3") %>%  
  add_trace( x=~time, y=~X4,type = "scatter",mode = "lines", name = "X4")  %>% layout(plot_bgcolor='#e5ecf6', title="Time series comparison of X with time", xaxis = list(title="Time"), yaxis = list(title="Input Signals"))

```

```{r}
fig1 = plot_ly(df, x=~time, y=~X1,type = "scatter",mode = "lines", name = "X1")
fig2 = plot_ly(df, x=~time, y=~X2,type = "scatter",mode = "lines", name = "X2")
fig3 = plot_ly(df, x=~time, y=~X3,type = "scatter",mode = "lines", name = "X3")
fig4 = plot_ly(df, x=~time, y=~X4,type = "scatter",mode = "lines", name = "X4")
x_fig = plotly:: subplot(fig1, fig2, fig3, fig4, nrows = 4, shareX = TRUE,titleX =TRUE, titleY = TRUE )  %>% layout(plot_bgcolor='#e5ecf6', title="Time series analysis of X with time", xaxis = list(title="Time"))
x_fig
```

```{r}

fig1 = plot_ly(df, x=~time, y=~y,type = "scatter",mode = "lines", name = "y")

y_fig = plotly:: subplot(fig1, nrows = 1,titleX =TRUE, titleY = TRUE )  %>% layout(plot_bgcolor='#e5ecf6', title="Time series analysis of Y with time", xaxis = list(title="Time"), yaxis = list(title="Output Signal Y"))
y_fig
```

```{r}
gg_X1 = ggplot(df, aes(x = X1)) +    # Draw histogram & density
  geom_histogram(aes(y = after_stat(density) ), bins=10,fill = "#195f90") + 
  stat_density(geom="line") +
  geom_rug()
ggplotly(gg_X1)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of X1", xaxis= list(title="X1 Signal"), yaxis = list(title="Density"))

```

```{r}
gg_X2 = ggplot(df, aes(x = X2)) +    # Draw histogram & density
  geom_histogram(aes(y = after_stat(density)), bins=10,fill = "#195f90") + 
  stat_density(geom="line") +
  geom_rug()
ggplotly(gg_X2)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of X2", xaxis= list(title="X2 Signal"), yaxis = list(title="Density"))

```

```{r}
gg_X3 = ggplot(df, aes(x = X3)) +    # Draw histogram & density
  geom_histogram(aes(y = after_stat(density)), bins=10,fill = "#195f90") + 
  stat_density(geom="line") +
  geom_rug()
ggplotly(gg_X3)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of X3", xaxis= list(title="X3 Signal"), yaxis = list(title="Density"))

```

```{r}
gg_X4 = ggplot(df, aes(x = X4)) +    # Draw histogram & density
  geom_histogram(aes(y = after_stat(density)), bins=10,fill = "#195f90") + 
  stat_density(aes(y = after_stat(density)),geom="line") +
  geom_rug()
ggplotly(gg_X4)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of X4", xaxis= list(title="X4 Signal"), yaxis = list(title="Density"))

```

```{r}
X_df = data.frame(rbind(data.frame(values = df$X1, Inputs = "X1"),
data.frame(values =df$X2, Inputs = "X2"),
data.frame(values= df$X3, Inputs = "X3"),
data.frame(values= df$X4, Inputs = "X4")))
```

```{r}
p <- ggplot(X_df, aes(x = values)) +
  geom_histogram(aes(x=values, y = after_stat(density), fill=Inputs), bins = 10, alpha=0.5)+
  stat_density(aes(x=values, y = after_stat(density), color=Inputs),geom="line") +
  geom_rug()
fig <- ggplotly(p) %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of X inputs", xaxis= list(title="X Signal"), yaxis = list(title="Density"))
p
```

```{r}
fig
```

```{r}
# Corelation
fig = plot_ly(df, x=~X1, y=~y, type="scatter", mode="markers") %>% layout(plot_bgcolor='#e5ecf6', title="Corelation of X1 input to y output", xaxis = list(title="X1 input"), yaxis = list(title="Output Signal Y"))
fig
```

```{r}
fig = plot_ly(df, x=~X2, y=~y, type="scatter", mode="markers") %>% layout(plot_bgcolor='#e5ecf6', title="Corelation of X2 input to y output", xaxis = list(title="X2 input"), yaxis = list(title="Output Signal Y"))
fig
```

```{r}
fig = plot_ly(df, x=~X3, y=~y, type="scatter", mode="markers") %>% layout(plot_bgcolor='#e5ecf6', title="Corelation of X3 input to y output", xaxis = list(title="X3 input"), yaxis = list(title="Output Signal Y"))
fig
```

```{r}
fig = plot_ly(df, x=~X4, y=~y, type="scatter", mode="markers") %>% layout(plot_bgcolor='#e5ecf6', title="Corelation of X4 input to y output", xaxis = list(title="X4 input"), yaxis = list(title="Output Signal Y"))
fig
```

```{r}
plot_ly(df) %>%
  add_trace( x=~X1, y=~y,type = "scatter",mode = "markers", name = "X1") %>%  
  add_trace( x=~X2, y=~y,type = "scatter",mode = "markers", name = "X2") %>%  
  add_trace( x=~X3, y=~y, type = "scatter",mode = "markers", name = "X3") %>%  
  add_trace( x=~X4, y=~y,type = "scatter",mode = "markers", name = "X4")  %>% layout(plot_bgcolor='#e5ecf6', title="Corelation of X inputs with y", xaxis = list(title="X inputs"), yaxis = list(title="Y"))

```

```{r}
thetaHat <- function(model, y){
  return (solve(t(model) %*% model) %*% t(model) %*% y)
}
```

```{r}
generateModel1 <- function(df){
  set.seed(100)
  ones = matrix(1, length(df$X1),1)
  noise  = rnorm(length(df$y), mean=0, sd = 0.1)
  theta_bias = runif(1, -1, 1) * ones
  return (cbind(df$X4, df$X1^2, df$X1^3, df$X2^4, df$X1^4, theta_bias, noise))
}

generateModel2 <- function(df){
  set.seed(100)
  ones = matrix(1, length(df$X1),1)
  noise  = rnorm(length(df$y), mean=0, sd = 0.1)
  theta_bias = runif(1, -1, 1) * ones
  return (cbind(df$X4, df$X1^3, df$X3^4, theta_bias, noise))
}

generateModel3 <- function(df){
  set.seed(100)
  ones = matrix(1, length(df$X1),1)
  noise  = rnorm(length(df$y), mean=0, sd = 0.1)
  theta_bias = runif(1, -1, 1) * ones
  return (cbind(df$X3^3, df$X3^4, theta_bias, noise))
}

generateModel4 <- function(df){
  set.seed(100)
  ones = matrix(1, length(df$X1),1)
  noise  = rnorm(length(df$y), mean=0, sd = 0.1)
  theta_bias = runif(1, -1, 1) * ones
  return (cbind(df$X2, df$X1^3, df$X3^4, theta_bias, noise))
}

generateModel5 <- function(df){
  set.seed(100)
  ones = matrix(1, length(df$X1),1)
  noise  = rnorm(length(df$y), mean=0, sd = 0.1)
  theta_bias = runif(1, -1, 1) * ones
  return (cbind(df$X4, df$X1^2, df$X1^3, df$X3^4, theta_bias, noise))
}
```

```{r}
Model1 = generateModel1(df)
Model1_theta_hat =thetaHat(Model1, df$y)
print("Model1 Theta hat")
print(Model1_theta_hat[,1])
print("Model1 Y hat")
y_Hat_Model1 = Model1 %*% Model1_theta_hat
print(y_Hat_Model1[1:5,])
```

```{r}
Model2 = generateModel2(df)
Model2_theta_hat = thetaHat(Model2, df$y)
print("Model2 Theta hat")
print(Model2_theta_hat[,1])
y_Hat_Model2 = Model2 %*% Model2_theta_hat
print("Model2 Y hat")
print(y_Hat_Model2[1:5,])
```

```{r}
Model3 = generateModel3(df)
Model3_theta_hat = thetaHat(Model3, df$y)
print("Model3 Theta hat")
print(Model3_theta_hat[,1])
y_Hat_Model3 = Model3 %*% Model3_theta_hat
print("Model3 Y hat")
print(y_Hat_Model3[1:5,])
```

```{r}
Model4 = generateModel4(df)
Model4_theta_hat = thetaHat(Model4, df$y)
print("Model4 Theta hat")
print(Model4_theta_hat[,1])
y_Hat_Model4 = Model4 %*% Model4_theta_hat
print("Model4 Y hat")
print(y_Hat_Model4[1:5,])
```

```{r}
Model5 = generateModel5(df)
Model5_theta_hat = thetaHat(Model5, df$y)
print("Model5 Theta hat")
print(Model5_theta_hat[,1])
y_Hat_Model5 = Model5 %*% Model5_theta_hat
print("Model5 Y hat")
print(y_Hat_Model5[1:5,])
```

```{r}
calculateRSS <- function(y, y_hat_model){
  return (sum((y-y_hat_model)^2))
}
```

```{r}
RSS_Model1 = calculateRSS(df$y, y_Hat_Model1)

RSS_Model2 = calculateRSS(df$y, y_Hat_Model2)

RSS_Model3 = calculateRSS(df$y, y_Hat_Model3)

RSS_Model4 = calculateRSS(df$y, y_Hat_Model4)

RSS_Model5 = calculateRSS(df$y, y_Hat_Model5)

c(RSS_Model1, RSS_Model2, RSS_Model3, RSS_Model4, RSS_Model5)

```

```{r}

```

```{r}
calculateVariance <- function(N, rss_model){
  return  (rss_model/(N-1))
}
calculateLikelihood <- function(N, variance_model, rss_model) {
  return (-(N/2)*(log(2*pi))-(N/2)*(log(variance_model))-(1/(2*variance_model))*rss_model)
}
N = length(df$y)
Variance_Model1 = calculateVariance(N, RSS_Model1)
Likelihood_1  = calculateLikelihood(N, Variance_Model1, RSS_Model1)
```

```{r}
N = length(df$y)
Variance_Model1 = calculateVariance(N, RSS_Model1)

Variance_Model2 = calculateVariance(N, RSS_Model2)

Variance_Model3 = calculateVariance(N, RSS_Model3)

Variance_Model4 = calculateVariance(N, RSS_Model4)

Variance_Model5 = calculateVariance(N, RSS_Model5)
```

```{r}
c(Variance_Model1, Variance_Model2, Variance_Model3, Variance_Model4, Variance_Model5)
```

```{r}
Likelihood_1  = calculateLikelihood(N, Variance_Model1, RSS_Model1)
Likelihood_2  = calculateLikelihood(N, Variance_Model2, RSS_Model2)
Likelihood_3  = calculateLikelihood(N, Variance_Model3, RSS_Model3)
Likelihood_4  = calculateLikelihood(N, Variance_Model4, RSS_Model4)
Likelihood_5  = calculateLikelihood(N, Variance_Model5, RSS_Model5)

c(Likelihood_1, Likelihood_2, Likelihood_3, Likelihood_4, Likelihood_5)
```

```{r}
calculateAIC <- function(N, model_thetahat, likelihood_model){
  k_model = length(model_thetahat)
  return (2*k_model-2*likelihood_model)
}

```

```{r}
calculateBIC <- function(N, model_thetahat, likelihood_model){
  k_model = length(model_thetahat)
  return (k_model* log(N) - 2*likelihood_model)
}
```

```{r}
AIC_Model1 = calculateAIC(N, Model1_theta_hat, Likelihood_1)
BIC_Model1 = calculateBIC(N, Model1_theta_hat, Likelihood_1)
c(AIC_Model1, BIC_Model1)
```

```{r}
AIC_Model2 = calculateAIC(N, Model2_theta_hat, Likelihood_2)
BIC_Model2 = calculateBIC(N, Model2_theta_hat, Likelihood_2)
c(AIC_Model2, BIC_Model2)
```

```{r}
AIC_Model3 = calculateAIC(N, Model3_theta_hat, Likelihood_3)
BIC_Model3 = calculateBIC(N, Model3_theta_hat, Likelihood_3)
c(AIC_Model3, BIC_Model3)
```

```{r}
AIC_Model4 = calculateAIC(N, Model4_theta_hat, Likelihood_4)
BIC_Model4 = calculateBIC(N, Model4_theta_hat, Likelihood_4)
c(AIC_Model4, BIC_Model4)
```

```{r}
AIC_Model5 = calculateAIC(N, Model5_theta_hat, Likelihood_5)
BIC_Model5 = calculateBIC(N, Model5_theta_hat, Likelihood_5)
c(AIC_Model5, BIC_Model5)
```

```{r}
list_models = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5")
list_aic = c(AIC_Model1, AIC_Model2, AIC_Model3, AIC_Model4, AIC_Model5)
list_bic = c(BIC_Model1, BIC_Model2, BIC_Model3, BIC_Model4, BIC_Model5)
list_rss = c(RSS_Model1, RSS_Model2, RSS_Model3, RSS_Model4, RSS_Model5)
list_likelihood = c(Likelihood_1, Likelihood_2, Likelihood_3, Likelihood_4, Likelihood_5)
list_variance = c(Variance_Model1, Variance_Model2, Variance_Model3, Variance_Model4, Variance_Model5)
```

```{r}
data.frame(Models = list_models, RSS = list_rss, AIC = list_aic, BIC = list_bic,  Likelihood = list_likelihood)

```

```{r}
data.frame(Models = list_models, AIC = list_aic)
```

```{r}
data.frame(Models = list_models, BIC = list_bic)

```

```{r}
data.frame(Models = list_models, RSS = list_rss)

```

```{r}
data.frame(Models = list_models, Variance = list_variance, Likelihood = list_likelihood)
```

```{r}
calculateError <- function(y, y_hat){
  return (y-y_hat)
}
```

```{r}
plotQQ <-function(model_error, title){
  error_fig = ggplot(data.frame(model_error), aes(sample=model_error)) +
  geom_qq(color = "#195f90" ) +
  geom_qq_line(color = "red" )
    
  return (ggplotly(error_fig)  %>% layout(plot_bgcolor='#e5ecf6', title=title, xaxis= list(title="Theoritical Quantities"), yaxis = list(title="Sample Quantities")))
}

```

```{r}
Model1_Error = calculateError(df$y, y_Hat_Model1)
plotQQ(Model1_Error, "QQ plot of model 1")
```

```{r}
Model2_Error = calculateError(df$y, y_Hat_Model2)
plotQQ(Model2_Error, "QQ plot of model 2")
```

```{r}
Model3_Error = calculateError(df$y, y_Hat_Model3)
plotQQ(Model3_Error, "QQ plot of model 3")

```

```{r}
Model4_Error = calculateError(df$y, y_Hat_Model4)
plotQQ(Model4_Error, "QQ plot of model 4")

```

```{r}
Model5_Error = calculateError(df$y, y_Hat_Model5)
plotQQ(Model5_Error, "QQ plot of model 5")
```

```{r}
set.seed(100)
Split_Data = initial_split(df, prop = .8)
training_set = training(Split_Data)
testing_set = testing(Split_Data)
```

```{r}
X_traning_model = generateModel5(training_set)
X_testing_model = generateModel5(testing_set)
training_thetaHat = thetaHat(X_traning_model, training_set$y)
```

```{r}
Y_testing_hat = X_testing_model %*% training_thetaHat
Y_training_hat = X_traning_model %*% training_thetaHat
```

```{r}
result = t.test(Y_training_hat, Y_testing_hat, mu = 500, alternative = "two.sided", conf.level=0.95)
result
```

```{r}
C_I1 = result$conf.int[1]
C_I2 = result$conf.int[2]
S_ERROR = result$stderr
S_ERROR
```

```{r}
traingin_plot = ggplot(training_set, aes(x = y)) +    # Draw histogram & density
  stat_density(geom="line", color = "#195f90") + 
  geom_vline(xintercept = C_I1, linetype="dashed", color="red")+ 
  geom_vline(xintercept = C_I2, linetype="dashed", color="red")+
  geom_vline(xintercept = S_ERROR, linetype="dashed", color="black")
ggplotly(traingin_plot)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of training data", xaxis= list(title="y"), yaxis = list(title="Density"))
```

```{r}
testing_plot = ggplot(testing_set, aes(x = y)) +    # Draw histogram & density
  stat_density(geom="line", color = "#195f90") + 
  geom_vline(xintercept = C_I1, linetype="dashed", color="red")+ 
  geom_vline(xintercept = C_I2, linetype="dashed", color="red")+
  geom_vline(xintercept = S_ERROR, linetype="dashed", color="black")
ggplotly(testing_plot)  %>% layout(plot_bgcolor='#e5ecf6', title="Distribution of testing data", xaxis= list(title="y"), yaxis = list(title="Density"))
```

```{r}
thetaHatTraining = thetaHat(X_traning_model, training_set$y)
```

```{r}
dis_test=density(training_set$y)
plot(dis_test,main = "Density plot of Y Signal")
```

```{r}
z=1.96 ##(95%) Confidential interval
error=(as.matrix(testing_set$y)- Y_testing_hat)
```

```{r}
n_len=length(Y_testing_hat)
sd_error = sqrt(abs(sum(error^2)/n_len -1))
sd_error


```

```{r}
C_I_1= z * sqrt( abs((error * (1-error) ) / n_len))
C_I_1
```

```{r}
C_I_2= z*sqrt(abs((error*(1+error)/n_len)))
C_I_2
```

```{r}
Model2_theta_hat[4,]
Model2_theta_hat
```

```{r}
arr_1=0
arr_2=0
f_value=0
s_value=0

thetebias <- Model2_theta_hat[4,] #choosen parameter
thetaone <- Model2_theta_hat[1,] # chosen prarameter
thetatwo <- Model2_theta_hat[2,]
thetathree <- -Model2_theta_hat[3,]
thetanoise <- Model2_theta_hat[5,]

epsilon <- RSS_Model2 * 2
num <- 100
```

```{r}
counter <- 0
for (i in 1:num) {
  p1 <- runif(1,-abs(thetebias),abs(thetebias))
  p2 <- runif(1,-abs(thetaone), abs(thetaone))
  abc_thetahat <- matrix(c(p1,p2,thetatwo,thetathree, thetanoise))
  abc_Y_Hat <- Model2 %*% abc_thetahat ## New Y hat
  abc_RSS <- sum((df$y-abc_Y_Hat)^2)
  
  if (abc_RSS > epsilon){
    arr_1[i] <- p1
    arr_2[i] <- p2
    counter = counter+1
    f_value <- matrix(arr_1)
    s_value <- matrix(arr_2)
  }
}
```

```{r}
abc_results = data.frame(f_value ,s_value)
```

```{r}
abc_results
```

```{r}
 plot_ly(abc_results, x=~f_value, y=~s_value, type="scatter", mode="markers") %>% layout(plot_bgcolor='#e5ecf6', title="Joint and Marginal Posterior Distribution", xaxis = list(title="ABC thetabias"), yaxis = list(title="ABC thetaone (X4)"))
```
